### ISSUE TITLE
[node] BigNumber error on deposit

### ISSUE THREAD

**Issue by rhlsthrm** [counterfactual/monorepo#2052]
Tested with version 0.2.29

The following error is thrown on the counterparty on deposit. For example, if our client deposits, the hub throws the error, and vice versa:

```
(node:83) UnhandledPromiseRejectionWarning: TypeError: initiatorBalanceDecrement.add is not a function
    at computeInterpreterParameters (/root/node_modules/@counterfactual/node/src/protocol/install.ts:440:44)
    at computeStateChannelTransition (/root/node_modules/@counterfactual/node/src/protocol/install.ts:299:7)
    at /root/node_modules/@counterfactual/node/src/protocol/install.ts:175:38
    at Generator.next (<anonymous>)
    at resume (/root/node_modules/@counterfactual/node/dist/index.js:53:44)
    at /root/node_modules/@counterfactual/node/dist/index.js:52:121
    at new Promise (<anonymous>)
```

**Comment by snario** [comment]
Are you certain the receiving party is on 0.2.29?

This line should be getting hit:

https://github.com/counterfactual/monorepo/blob/9edb1fe8eb517475144ba2515fd66a93ec80b2a8/packages/node/src/message-handling/handle-protocol-message.ts#L43
