### ISSUE TITLE
[contracts] Running Truffle tests on Windows fails

### ISSUE THREAD

**Issue by Alonski** [counterfactual/monorepo#303]
The script to run truffle tests is:
`"test": "tsc -b && truffle test --network ganache $npm_package_config_testFiles",`
This uses a config to output this command:
`tsc -b && truffle test --network ganache dist/test/**/*.spec.js`

On Windows this is failing with:
```
Error: Cannot find module 'C:\Users\Alon\Documents\Projects\Prototypal\counterfactual\monorepo\packages\contracts\dist\test\**\*.spec.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:587:15)
    at Function.Module._load (internal/modules/cjs/loader.js:513:25)
    at Module.require (internal/modules/cjs/loader.js:643:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at C:\Users\Alon\Documents\Projects\Prototypal\counterfactual\monorepo\node_modules\mocha\lib\mocha.js:231:27
    at Array.forEach (<anonymous>)
    at Mocha.loadFiles (C:\Users\Alon\Documents\Projects\Prototypal\counterfactual\monorepo\node_modules\mocha\lib\mocha.js:228:14)
    at Mocha.run (C:\Users\Alon\Documents\Projects\Prototypal\counterfactual\monorepo\node_modules\mocha\lib\mocha.js:536:10)
    at C:\Users\Alon\Documents\Projects\Prototypal\counterfactual\monorepo\node_modules\truffle\build\webpack:\packages\truffle-core\lib\test.js:120:1
    at process.internalTickCallback (internal/process/next_tick.js:77:7)
error Command failed with exit code 1.
```

**Comment by snario** [comment]
#163 fixed this
