### ISSUE TITLE
Decorator syntax produces weird transpilation that the PG server fails to use

### ISSUE THREAD

**Issue by cf19drofxots** [counterfactual/monorepo#811]
```
ReferenceError: RequestHandler is not defined

      30 |   @ChannelCreator.enqueue
      31 |   static async executeMethod(
    > 32 |     requestHandler: RequestHandler,
         |                     ^
      33 |     params: Node.CreateChannelParams
      34 |   ): Promise<Node.CreateChannelResult> {
      35 |     const multisigAddress = await deployMinimumViableMultisigAndGetAddress(

      at Object.<anonymous> (../node/src/methods/state-channel/create/controller.ts:32:21)
      at Object.<anonymous> (src/node.ts:1:1)
      at Object.<anonymous> (src/resources/matchmaking-request/processor.ts:5:1)
      at Object.<anonymous> (src/api.ts:9:1)
```

Note that the `RequestHandler` is in fact defined, otherwise the `Node` package's build would have failed.

**Comment by snario** [comment]
Changed the implementation to not use a decorator #804
